server:
  port: 9999
spring:
  datasource:
    username: root
    password: 1234567890
    url: jdbc:mysql://localhost:3307/x_user
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1